// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modelo;

#nullable disable

namespace Modelo.Migrations
{
    [DbContext(typeof(SistemaBibliotecario))]
    [Migration("20251016183233_Auditoria")]
    partial class Auditoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entidades.Auditoria", b =>
                {
                    b.Property<int>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditoriaId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorAnterior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorNuevo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditoriaId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("Entidades.ClassLibrosParaComprar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Contador")
                        .HasColumnType("int");

                    b.Property<string>("TextoCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LibrosParaComprar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contador = 0,
                            TextoCompleto = "Título Genérico 1 - Autor Genérico 1"
                        });
                });

            modelBuilder.Entity("Entidades.CuotaMensual", b =>
                {
                    b.Property<int>("CuotaMensualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuotaMensualId"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroMes")
                        .HasColumnType("int");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CuotaMensualId");

                    b.ToTable("CuotasMensuales");

                    b.HasData(
                        new
                        {
                            CuotaMensualId = 1,
                            Año = 2024,
                            Mes = "Enero",
                            NumeroMes = 1,
                            Valor = 2000.00m
                        },
                        new
                        {
                            CuotaMensualId = 2,
                            Año = 2024,
                            Mes = "Febrero",
                            NumeroMes = 2,
                            Valor = 2000.00m
                        },
                        new
                        {
                            CuotaMensualId = 3,
                            Año = 2024,
                            Mes = "Marzo",
                            NumeroMes = 3,
                            Valor = 2000.00m
                        },
                        new
                        {
                            CuotaMensualId = 4,
                            Año = 2024,
                            Mes = "Abril",
                            NumeroMes = 4,
                            Valor = 2000.00m
                        },
                        new
                        {
                            CuotaMensualId = 5,
                            Año = 2024,
                            Mes = "Mayo",
                            NumeroMes = 5,
                            Valor = 2000.00m
                        },
                        new
                        {
                            CuotaMensualId = 6,
                            Año = 2024,
                            Mes = "Junio",
                            NumeroMes = 6,
                            Valor = 2000m
                        });
                });

            modelBuilder.Entity("Entidades.DetallePago", b =>
                {
                    b.Property<int>("DetallePagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetallePagoId"));

                    b.Property<int>("CuotaMensualId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoCobrado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.HasKey("DetallePagoId");

                    b.HasIndex("CuotaMensualId");

                    b.HasIndex("SocioId");

                    b.ToTable("DetallesPagos");

                    b.HasData(
                        new
                        {
                            DetallePagoId = 1,
                            CuotaMensualId = 1,
                            FechaPago = new DateTime(2025, 10, 16, 15, 32, 32, 642, DateTimeKind.Local).AddTicks(8125),
                            MontoCobrado = 2000.00m,
                            SocioId = 1
                        },
                        new
                        {
                            DetallePagoId = 2,
                            CuotaMensualId = 2,
                            FechaPago = new DateTime(2025, 10, 16, 15, 32, 32, 642, DateTimeKind.Local).AddTicks(8128),
                            MontoCobrado = 2000.00m,
                            SocioId = 2
                        },
                        new
                        {
                            DetallePagoId = 3,
                            CuotaMensualId = 3,
                            FechaPago = new DateTime(2025, 10, 16, 15, 32, 32, 642, DateTimeKind.Local).AddTicks(8130),
                            MontoCobrado = 2000.00m,
                            SocioId = 3
                        });
                });

            modelBuilder.Entity("Entidades.Devolucion", b =>
                {
                    b.Property<int>("DevolucionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DevolucionId"));

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("int");

                    b.HasKey("DevolucionId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("Devoluciones");

                    b.HasData(
                        new
                        {
                            DevolucionId = 1,
                            FechaDevolucion = new DateTime(2025, 10, 13, 15, 32, 32, 642, DateTimeKind.Local).AddTicks(8021),
                            PrestamoId = 1
                        },
                        new
                        {
                            DevolucionId = 2,
                            FechaDevolucion = new DateTime(2025, 10, 14, 15, 32, 32, 642, DateTimeKind.Local).AddTicks(8022),
                            PrestamoId = 2
                        },
                        new
                        {
                            DevolucionId = 3,
                            FechaDevolucion = new DateTime(2025, 10, 15, 15, 32, 32, 642, DateTimeKind.Local).AddTicks(8024),
                            PrestamoId = 3
                        });
                });

            modelBuilder.Entity("Entidades.Libro", b =>
                {
                    b.Property<int>("LibroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibroId"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LibroId");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            LibroId = 1,
                            Autor = "Gabriel García Márquez",
                            Disponible = true,
                            Titulo = "Cien años de soledad",
                            Ubicacion = "M1"
                        },
                        new
                        {
                            LibroId = 2,
                            Autor = "Miguel de Cervantes",
                            Disponible = true,
                            Titulo = "Don Quijote de la Mancha",
                            Ubicacion = "C1"
                        },
                        new
                        {
                            LibroId = 3,
                            Autor = "Antoine de Saint-Exupéry",
                            Disponible = true,
                            Titulo = "El principito",
                            Ubicacion = "S1"
                        });
                });

            modelBuilder.Entity("Entidades.Multa", b =>
                {
                    b.Property<int>("MultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MultaId"));

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Pagada")
                        .HasColumnType("bit");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.HasKey("MultaId");

                    b.HasIndex("SocioId");

                    b.ToTable("Multas");

                    b.HasData(
                        new
                        {
                            MultaId = 1,
                            FechaFinalizacion = new DateTime(2025, 10, 13, 15, 32, 32, 642, DateTimeKind.Local).AddTicks(8064),
                            FechaInicio = new DateTime(2025, 10, 13, 15, 32, 32, 642, DateTimeKind.Local).AddTicks(8063),
                            Pagada = true,
                            SocioId = 1
                        });
                });

            modelBuilder.Entity("Entidades.Prestamo", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestamoId"));

                    b.Property<int>("CarritoId")
                        .HasColumnType("int");

                    b.Property<bool>("EnPrestamo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.HasKey("PrestamoId");

                    b.HasIndex("LibroId");

                    b.HasIndex("SocioId");

                    b.ToTable("Prestamos");

                    b.HasData(
                        new
                        {
                            PrestamoId = 1,
                            CarritoId = 1,
                            EnPrestamo = true,
                            FechaDevolucion = new DateTime(2025, 10, 6, 15, 32, 32, 642, DateTimeKind.Local).AddTicks(7989),
                            FechaPrestamo = new DateTime(2025, 10, 6, 15, 32, 32, 642, DateTimeKind.Local).AddTicks(7973),
                            LibroId = 1,
                            SocioId = 1
                        },
                        new
                        {
                            PrestamoId = 2,
                            CarritoId = 2,
                            EnPrestamo = true,
                            FechaDevolucion = new DateTime(2025, 10, 11, 15, 32, 32, 642, DateTimeKind.Local).AddTicks(7995),
                            FechaPrestamo = new DateTime(2025, 10, 11, 15, 32, 32, 642, DateTimeKind.Local).AddTicks(7994),
                            LibroId = 2,
                            SocioId = 2
                        },
                        new
                        {
                            PrestamoId = 3,
                            CarritoId = 3,
                            EnPrestamo = true,
                            FechaDevolucion = new DateTime(2025, 10, 13, 15, 32, 32, 642, DateTimeKind.Local).AddTicks(7998),
                            FechaPrestamo = new DateTime(2025, 10, 13, 15, 32, 32, 642, DateTimeKind.Local).AddTicks(7997),
                            LibroId = 3,
                            SocioId = 3
                        });
                });

            modelBuilder.Entity("Entidades.Regla", b =>
                {
                    b.Property<int>("ReglaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReglaId"));

                    b.Property<int>("DiasMulta")
                        .HasColumnType("int");

                    b.Property<int>("DiasPrestamo")
                        .HasColumnType("int");

                    b.Property<int>("DiasVencimientoCuota")
                        .HasColumnType("int");

                    b.Property<int>("MaxLibrosPorUsuario")
                        .HasColumnType("int");

                    b.Property<int>("PorcentajeRecargoCuota")
                        .HasColumnType("int");

                    b.HasKey("ReglaId");

                    b.ToTable("Reglas");

                    b.HasData(
                        new
                        {
                            ReglaId = 1,
                            DiasMulta = 7,
                            DiasPrestamo = 7,
                            DiasVencimientoCuota = 10,
                            MaxLibrosPorUsuario = 3,
                            PorcentajeRecargoCuota = 10
                        });
                });

            modelBuilder.Entity("Entidades.Socio", b =>
                {
                    b.Property<int>("SocioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocioId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CantidadLibros")
                        .HasColumnType("int");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MultadoHasta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SocioId");

                    b.ToTable("Socios");

                    b.HasData(
                        new
                        {
                            SocioId = 1,
                            Apellido = "González",
                            CantidadLibros = 1,
                            Dni = 12345678,
                            FechaIngreso = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Habilitado = true,
                            Nombre = "Ana"
                        },
                        new
                        {
                            SocioId = 2,
                            Apellido = "Martínez",
                            CantidadLibros = 1,
                            Dni = 87654321,
                            FechaIngreso = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Habilitado = true,
                            Nombre = "Juan"
                        },
                        new
                        {
                            SocioId = 3,
                            Apellido = "López",
                            CantidadLibros = 1,
                            Dni = 98765432,
                            FechaIngreso = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Habilitado = true,
                            Nombre = "María"
                        });
                });

            modelBuilder.Entity("Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ClaveModificada")
                        .HasColumnType("bit");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreDeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PalabraDeSeguridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PuedeBorrarLibros")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeBorrarSocios")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeCambiarReglas")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeCobrarCuotas")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeGestionarUsuarios")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeModificarLibros")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeModificarSocios")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeModificarValorCuota")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeVerRegistros")
                        .HasColumnType("bit");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Activo = true,
                            Apellido = "Villalva",
                            Clave = "27029674",
                            ClaveModificada = false,
                            Dni = "27029674",
                            Nombre = "Javier",
                            NombreDeUsuario = "27029674",
                            PalabraDeSeguridad = "seguridad",
                            PuedeBorrarLibros = true,
                            PuedeBorrarSocios = true,
                            PuedeCambiarReglas = true,
                            PuedeCobrarCuotas = true,
                            PuedeGestionarUsuarios = true,
                            PuedeModificarLibros = true,
                            PuedeModificarSocios = true,
                            PuedeModificarValorCuota = true,
                            PuedeVerRegistros = true,
                            Rol = "Administrador"
                        },
                        new
                        {
                            UsuarioId = 2,
                            Activo = true,
                            Apellido = "Pérez",
                            Clave = "12345678",
                            ClaveModificada = false,
                            Dni = "12345678",
                            Nombre = "Carlos",
                            NombreDeUsuario = "12345678",
                            PalabraDeSeguridad = "otraPalabraSegura456",
                            PuedeBorrarLibros = false,
                            PuedeBorrarSocios = false,
                            PuedeCambiarReglas = false,
                            PuedeCobrarCuotas = false,
                            PuedeGestionarUsuarios = false,
                            PuedeModificarLibros = false,
                            PuedeModificarSocios = false,
                            PuedeModificarValorCuota = false,
                            PuedeVerRegistros = false,
                            Rol = "Bibliotecario"
                        });
                });

            modelBuilder.Entity("Entidades.DetallePago", b =>
                {
                    b.HasOne("Entidades.CuotaMensual", "CuotaMensual")
                        .WithMany("DetallePagos")
                        .HasForeignKey("CuotaMensualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Socio", "Socio")
                        .WithMany("DetallePagos")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuotaMensual");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Entidades.Devolucion", b =>
                {
                    b.HasOne("Entidades.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("Entidades.Multa", b =>
                {
                    b.HasOne("Entidades.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Entidades.Prestamo", b =>
                {
                    b.HasOne("Entidades.Libro", "Libro")
                        .WithMany()
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Libro");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Entidades.CuotaMensual", b =>
                {
                    b.Navigation("DetallePagos");
                });

            modelBuilder.Entity("Entidades.Socio", b =>
                {
                    b.Navigation("DetallePagos");
                });
#pragma warning restore 612, 618
        }
    }
}
